### ISSUE TITLE
How to fix issue with Memroy size!

### ISSUE THREAD

**Issue by GoogleCodeExporter** [senderle/topic-modeling-tool#13]
```
What steps will reproduce the problem?
1. Using Yelp dataset with 1 + Million documents 
2. Heap memory size is

What is the expected output? What do you see instead?
It should write the result to the output file

What version of the product are you using? On what operating system?
Recent one

Please provide any additional information below.

Is there any way to fix this issue with memory size / limit? while testing with 
large data. 
```

Original issue reported on code.google.com by `milsonmu...@u.boisestate.edu` on 29 Mar 2015 at 10:49

Attachments:
* [error.png](https://storage.googleapis.com/google-code-attachments/topic-modeling-tool/issue-13/comment-0/error.png)

**Comment by senderle** [comment]
I would bet that MALLET can't handle 1+ million documents. But even if it can, this is probably outside of the reasonable scope for an exploratory tool like this. (This could also be a memory settings issue, in which case the fix is to increase the amount of memory available to your JVM.) 

Closing for now. Will reopen and investigate in the future if it seems necessary.
