### ISSUE TITLE
Stop word list 

### ISSUE THREAD

**Issue by GoogleCodeExporter** [senderle/topic-modeling-tool#9]
```
We are using this tool and wish to add words to the stop word list. Is there 
anywhere that we can download the stop word list/file so that we can add some 
words and use the updated list as our stop word list?   


```

Original issue reported on code.google.com by `gregcfis...@gmail.com` on 3 Mar 2014 at 8:51

**Comment by senderle** [comment]
This is a potential problem with the tool; perhaps it ought to be possible to add additional stopwords via MALLET's  `--extra-stopwords` option. I'll look into that possibility. In the meanwhile, just look at the MALLET repo; there's a [folder](https://github.com/mimno/Mallet/tree/master/stoplists) with the stopword

**Comment by senderle** [comment]
This has been "fixed." It's not perfect; you can combine MALLET's default list with your own now, but if you then turn off MALLET's list, you can't turn it back on. I don't know why turning it back on doesn't work, but since it doesn't, we go so far as to disable that option once it's gone. A really decent fix will require more work, and I'm going to make that it's own issue.
